# code: language=ansible

# Set of tasks for creating performing a Trilio for Kubernetes Restore when using kubeconfig
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Restore Tasks
  tags: ['restore', 'smoketest']
  block:
    - name: Configure the restore {{ restore_info }}
      ansible.builtin.template:
        src: templates/restore.yaml.j2
        dest: "/tmp/{{ item.backup_name }}-restore.yaml"
        mode: "0640"
      loop: "{{ restore_info }}"

    # Execute the specified backup restore in specifed namespace
    - name: Execute the restore of {{ restore_info }}
      kubernetes.core.k8s:
        kind: Restore
        state: present
        namespace: "{{ item.restore_namespace }}"
        src: "/tmp/{{ item.backup_name }}-restore.yaml"
        validate_certs: false
      register: trilio_kubernetes_restore
      loop: "{{ restore_info }}"

    - name: Get restore from namespaces
      loop: "{{ restore_info }}"
      kubernetes.core.k8s_info:
        api_version: "triliovault.trilio.io/v1"
        kind: Restore
        namespace: "{{ item.restore_namespace }}"
        name: "{{ item.backup_name }}-restore-{{ trilio_kubernetes_uniq_id }}"
        validate_certs: false
      register: restores
      retries: 10
      delay: 60
      until: restores.resources is defined and
        restores.resources | length > 0 and
        restores.resources[0].status is defined and
        restores.resources[0].status.status is defined and
        restores.resources[0].status.status == 'Completed'
